project:
  type: book

book:
  title: "Unofficial NWFSC/SWFSC Groundfish Stock Assessment Handbook"
  author: "Assessment teams at NWFSC and SWFSC"
  date: last-modified
  
  site-url: https://pfmc-assessments.github.io/pfmc_assessment_handbook/
  repo-url: https://github.com/pfmc-assessments/pfmc_assessment_handbook
  repo-actions: [edit,issue]
  
  chapters:
    - index.qmd
    - 01-data-sources.qmd
    - 02-model-choices.qmd
    - 03-stock-synthesis.qmd
    - 04-post-model.qmd
    - 05-other.qmd
  appendices:
    - appendix-a.qmd
    - appendix-b.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
  pdf:
    documentclass: scrreprt
    number-sections: true

editor: visual

